import Head from "next/head";
import { Button } from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={"text-center"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="text-center font-bold text-2xl">
          NextJS + TailwindCSS + Typescript + Storybook + Cypress Template 🍽
        </h1>
        <Button colorScheme="purple">Hello</Button>
      </main>

      <footer className={"bg-gray-200 p-2"}>
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://github.com/litmus-zhang"
        >
          Created by <span className={"text-blue-500"}>@litmus-zhang</span>
        </a>
      </footer>
    </div>
  );
}
